# These are supported funding model platforms

github: [yksanjo]
# patreon: # Replace with your Patreon
# open_collective: # Replace with your Open Collective
# ko_fi: # Replace with your Ko-fi
# tidelift: # Replace with your Tidelift
# community_bridge: # Replace with your Community Bridge
# liberapay: # Replace with your Liberapay
# issuehunt: # Replace with your IssueHunt
# otechie: # Replace with your Otechie
# custom: ['https://www.buymeacoffee.com/yksanjo']
